import React,{useEffect,useState,useRef} from 'react';
import {SafeAreaView,ScrollView,View,Text,Switch,BackHandler,Platform,StatusBar} from 'react-native';
import {Label,Action,Field,Card,ErrorMessage,palette} from './ui';
import AuthScreens from './AuthScreens';
import ApiScreen from './ApiScreen';
import NotificationsScreen from './NotificationsScreen';
import SavedProgressScreen from './SavedProgressScreen';
import {loadGarden,saveGarden,initialState} from './storage';
import {signupError,normalizeEmail,createCredentials,matchesPassword} from './auth';
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
const seeds=()=>[{id:'walk',name:'Morning walk',description:'Walk for 15 minutes after breakfast.',days:[]},{id:'read',name:'Read 10 pages',description:'Make time for a book you enjoy.',days:[]},{id:'water',name:'Drink water',description:'Take a refreshing water break.',days:[]}];
export default function App(){
  const [data,setData]=useState(initialState),[ready,setReady]=useState(false),[fatal,setFatal]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[route,setRoute]=useState('login'),[stack,setStack]=useState([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[displayName,setDisplayName]=useState('');
  const latest=useRef(initialState),lock=useRef(false);
  const account=data.accounts.find(a=>a.email===data.session),dark=account?.dark===true;
  async function load(){setFatal('');setReady(false);try{const saved=await loadGarden();latest.current=saved;setData(saved);setRoute(saved.session?'home':'login');setStack([]);}catch(e){setFatal(e.message||'Unable to read storage.');}finally{setReady(true);}}
  useEffect(()=>{load();},[]);
  function go(next){setError('');setStack(s=>[...s,route]);setRoute(next);}
  function back(){setError('');setRoute(stack[stack.length-1]||'home');setStack(s=>s.slice(0,-1));}
  useEffect(()=>{if(Platform.OS==='web')return;const h=BackHandler.addEventListener('hardwareBackPress',()=>{if(stack.length){back();return true;}return false;});return()=>h.remove();},[stack]);
  async function commit(update){if(lock.current)throw new Error('A change is still saving. Please wait.');lock.current=true;setSaving(true);try{const next=update(latest.current);await saveGarden(next);latest.current=next;setData(next);}finally{lock.current=false;setSaving(false);}}
  async function safely(fn){setError('');try{await fn();}catch(e){setError(e.message||'Unable to save. Your previous data is unchanged.');}}
  async function signup(username,email,password){const invalid=signupError(username,email,password);if(invalid)throw new Error(invalid);const normalized=normalizeEmail(email);if(latest.current.accounts.some(a=>a.email===normalized))throw new Error('An account with this email already exists.');const credentials=await createCredentials(password);await commit(d=>({...d,session:normalized,accounts:[...d.accounts,{username:username.trim(),email:normalized,...credentials,dark:false,habits:seeds()}]}));setRoute('home');setStack([]);}
  async function login(email,password){const normalized=normalizeEmail(email),found=latest.current.accounts.find(a=>a.email===normalized);if(!found||!await matchesPassword(found,password))throw new Error('Login unsuccessful. Check your email and password.');await commit(d=>({...d,session:normalized}));setRoute('home');setStack([]);}
  async function updateAccount(fn){await commit(d=>({...d,accounts:d.accounts.map(a=>a.email===d.session?fn(a):a)}));}
  async function logout(){await commit(d=>({...d,session:null}));setRoute('login');setStack([]);}
  const habit=account?.habits.find(h=>h.id===selected);
  let content;
  if(!ready)content=<Label>Loading your garden…</Label>;
  else if(fatal)content=<><ErrorMessage>{fatal}</ErrorMessage><Label>Your saved data has been preserved.</Label><Action label="Retry loading" onPress={load}/></>;
  else if(!account)content=<AuthScreens key={route} mode={route} onNavigate={next=>{setRoute(next);setStack([]);}} onSignup={signup} onLogin={login}/>;
  else if(route==='home')content=<><Label large>Your garden</Label><Card><Label>{account.habits.filter(h=>h.days.includes(today())).length} of {account.habits.length} done today</Label><Label muted>Choose a habit, then mark it complete. Your progress saves automatically.</Label></Card>{account.habits.map(h=><Action key={h.id} label={`${h.name}${h.days.includes(today())?' ✓':''} · View habit`} onPress={()=>{setSelected(h.id);go('detail');}}/>)}<Action label="+ Add a habit" onPress={()=>{setName('');setDescription('');go('add');}}/><Action secondary label="Inspiration" onPress={()=>go('api')}/><Action secondary label="Profile" onPress={()=>go('profile')}/></>;
  else if(route==='detail')content=habit?<><Label large>{habit.name}</Label><Card><Label>{habit.description||'Make a small step today.'}</Label><Label muted>Schedule: Every day</Label></Card><Label>Completed: {habit.days.length} days</Label><Label>Today: {habit.days.includes(today())?'Completed':'Not completed'}</Label><Action disabled={saving} label={habit.days.includes(today())?'Undo today’s completion':'Mark complete today'} onPress={()=>safely(()=>updateAccount(a=>({...a,habits:a.habits.map(h=>h.id===selected?{...h,days:h.days.includes(today())?h.days.filter(d=>d!==today()):[...h.days,today()]}:h)})))}/><Label muted>Progress is saved on this device.</Label></>:<Label>Habit not found. Return to your garden.</Label>;
  else if(route==='add')content=<><Label large>Plant a new habit</Label><Field label="Habit name" value={name} onChangeText={setName}/><Field label="Description" value={description} onChangeText={setDescription} multiline/><Action disabled={saving} label="Save habit" onPress={()=>safely(async()=>{if(!name.trim())throw new Error('Enter a habit name.');if(name.trim().length>80)throw new Error('Keep the habit name under 80 characters.');await updateAccount(a=>({...a,habits:[...a.habits,{id:`h-${Date.now()}`,name:name.trim(),description:description.trim(),days:[]}]}));back();})}/></>;
  else if(route==='profile')content=<><Label large>Your profile</Label><Card><Label>{account.username}</Label><Label muted>{account.email}</Label></Card><Card><Label>Your progress</Label><Label>{account.habits.length} habits · {account.habits.reduce((n,h)=>n+h.days.length,0)} completed days</Label></Card><Label muted>Your profile, habits and settings are stored locally on this device.</Label><Action label="View saved progress" onPress={()=>go('saved')}/><Action label="Settings" onPress={()=>{setDisplayName(account.username);go('settings');}}/></>;
  else if(route==='saved')content=<SavedProgressScreen/>;
  else if(route==='api')content=<ApiScreen/>;
  else if(route==='menu')content=<><Label large>Menu</Label>{[['Home','home'],['Profile','profile'],['Inspiration','api'],['Settings','settings'],['Notifications','notifications']].map(([label,key])=><Action key={key} label={label} onPress={()=>{if(key==='settings')setDisplayName(account.username);go(key);}}/>)}<Action secondary label="Log out" disabled={saving} onPress={()=>safely(logout)}/></>;
  else if(route==='settings')content=<><Label large>Settings</Label><Field label="Display name" value={displayName} onChangeText={setDisplayName}/><Action disabled={saving} label="Save profile" onPress={()=>safely(async()=>{if(displayName.trim().length<2)throw new Error('Enter at least 2 characters.');await updateAccount(a=>({...a,username:displayName.trim()}));})}/><Card><Label>Dark theme</Label><Switch accessibilityLabel="Dark theme" value={dark} disabled={saving} onValueChange={value=>safely(()=>updateAccount(a=>({...a,dark:value})))}/></Card><Action label="Manage notifications" onPress={()=>go('notifications')}/><Label muted>Habit Garden · Version 1.0 · Local learning prototype. No cloud synchronization.</Label></>;
  else if(route==='notifications')content=<NotificationsScreen/>;
  else content=<Action label="Back to garden" onPress={()=>{setRoute('home');setStack([]);}}/>;
  return <SafeAreaView style={{flex:1,backgroundColor:dark?'#17221b':palette.bg,paddingTop:Platform.OS==='android'?StatusBar.currentHeight:0}}><StatusBar barStyle={dark?'light-content':'dark-content'}/><ScrollView contentContainerStyle={{width:'100%',maxWidth:440,alignSelf:'center',padding:24,paddingBottom:48,gap:20}} keyboardShouldPersistTaps="handled"><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12}}><Text style={{fontWeight:'700',letterSpacing:1,color:dark?'#d8ecd1':'#395e39'}}>HABIT GARDEN</Text>{account&&<Action label="☰ Menu" secondary onPress={()=>go('menu')}/>}</View><View style={{backgroundColor:palette.bg,padding:dark?16:0,borderRadius:18,gap:20}}>{content}<ErrorMessage>{error}</ErrorMessage>{saving&&<Label muted>Saving…</Label>}{account&&route!=='home'&&<Action secondary label="‹ Back" disabled={saving} onPress={back}/>}</View></ScrollView></SafeAreaView>;
}
