import React from 'react';
import {View,Text,Pressable,TextInput,StyleSheet} from 'react-native';
export const palette={bg:'#fafaf5',text:'#192e21',muted:'#52685b',card:'#e8f2e3',accent:'#6750a4',border:'#7b857e',error:'#a52828',white:'#fff'};
export function Label({children,large=false,muted=false}) {return <Text style={[styles.text,large&&styles.title,muted&&styles.muted]}>{children}</Text>;}
export function Action({label,onPress,disabled=false,secondary=false}) {return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,secondary&&styles.secondary,disabled&&{opacity:.5},pressed&&{opacity:.8}]}><Text style={[styles.buttonText,secondary&&{color:palette.accent}]}>{label}</Text></Pressable>;}
export function Field({label,value,onChangeText,secure=false,multiline=false}) {return <View style={{gap:6}}><Label>{label}</Label><TextInput accessibilityLabel={label} placeholder={label} value={value} onChangeText={onChangeText} secureTextEntry={secure} multiline={multiline} autoCapitalize={label.toLowerCase().includes('email')?'none':'sentences'} keyboardType={label.toLowerCase().includes('email')?'email-address':'default'} style={[styles.input,multiline&&{minHeight:90}]} /></View>;}
export function Card({children}){return <View style={styles.card}>{children}</View>;}
export function ErrorMessage({children}){return children?<Text accessibilityRole="alert" style={styles.error}>{children}</Text>:null;}
export const styles=StyleSheet.create({text:{fontSize:16,lineHeight:24,color:palette.text},title:{fontSize:30,lineHeight:39,fontWeight:'700'},muted:{color:palette.muted},button:{minHeight:48,padding:12,paddingHorizontal:20,backgroundColor:palette.accent,borderRadius:24,alignItems:'center',justifyContent:'center'},buttonText:{color:palette.white,fontWeight:'600',fontSize:16,textAlign:'center'},secondary:{backgroundColor:'#eee9f8'},input:{borderWidth:1,borderColor:palette.border,borderRadius:8,padding:14,fontSize:16,color:palette.text,backgroundColor:'#fff',minHeight:52},card:{backgroundColor:palette.card,padding:18,borderRadius:18,gap:10},error:{fontSize:15,color:palette.error,lineHeight:22}});
